//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4thIR.Custom.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_4thIR.Custom.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performs classification of documents..
        /// </summary>
        public static string DocumentClassificationKYC_Description {
            get {
                return ResourceManager.GetString("DocumentClassificationKYC_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Classification.
        /// </summary>
        public static string DocumentClassificationKYC_DisplayName {
            get {
                return ResourceManager.GetString("DocumentClassificationKYC_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of the document classification..
        /// </summary>
        public static string DocumentClassificationKYC_DocumentClass_Description {
            get {
                return ResourceManager.GetString("DocumentClassificationKYC_DocumentClass_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Class.
        /// </summary>
        public static string DocumentClassificationKYC_DocumentClass_DisplayName {
            get {
                return ResourceManager.GetString("DocumentClassificationKYC_DocumentClass_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file format of the document..
        /// </summary>
        public static string DocumentClassificationKYC_DocumentType_Description {
            get {
                return ResourceManager.GetString("DocumentClassificationKYC_DocumentType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        public static string DocumentClassificationKYC_DocumentType_DisplayName {
            get {
                return ResourceManager.GetString("DocumentClassificationKYC_DocumentType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path to the document file..
        /// </summary>
        public static string DocumentClassificationKYC_FilePath_Description {
            get {
                return ResourceManager.GetString("DocumentClassificationKYC_FilePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        public static string DocumentClassificationKYC_FilePath_DisplayName {
            get {
                return ResourceManager.GetString("DocumentClassificationKYC_FilePath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performs classification of images..
        /// </summary>
        public static string ImageClassificationCV_Description {
            get {
                return ResourceManager.GetString("ImageClassificationCV_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Classification.
        /// </summary>
        public static string ImageClassificationCV_DisplayName {
            get {
                return ResourceManager.GetString("ImageClassificationCV_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of the image classification..
        /// </summary>
        public static string ImageClassificationCV_Label_Description {
            get {
                return ResourceManager.GetString("ImageClassificationCV_Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string ImageClassificationCV_Label_DisplayName {
            get {
                return ResourceManager.GetString("ImageClassificationCV_Label_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path to the image file..
        /// </summary>
        public static string ImageClassificationCV_Path_Description {
            get {
                return ResourceManager.GetString("ImageClassificationCV_Path_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string ImageClassificationCV_Path_DisplayName {
            get {
                return ResourceManager.GetString("ImageClassificationCV_Path_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performs classification of images..
        /// </summary>
        public static string ImageClassificationR50_Description {
            get {
                return ResourceManager.GetString("ImageClassificationR50_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Classification.
        /// </summary>
        public static string ImageClassificationR50_DisplayName {
            get {
                return ResourceManager.GetString("ImageClassificationR50_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of the image classification..
        /// </summary>
        public static string ImageClassificationR50_Label_Description {
            get {
                return ResourceManager.GetString("ImageClassificationR50_Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string ImageClassificationR50_Label_DisplayName {
            get {
                return ResourceManager.GetString("ImageClassificationR50_Label_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path to the image file..
        /// </summary>
        public static string ImageClassificationR50_Path_Description {
            get {
                return ResourceManager.GetString("ImageClassificationR50_Path_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string ImageClassificationR50_Path_DisplayName {
            get {
                return ResourceManager.GetString("ImageClassificationR50_Path_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performs classification of images..
        /// </summary>
        public static string ImageClassificationVissl_Description {
            get {
                return ResourceManager.GetString("ImageClassificationVissl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Classification.
        /// </summary>
        public static string ImageClassificationVissl_DisplayName {
            get {
                return ResourceManager.GetString("ImageClassificationVissl_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of the image classification..
        /// </summary>
        public static string ImageClassificationVissl_Label_Description {
            get {
                return ResourceManager.GetString("ImageClassificationVissl_Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string ImageClassificationVissl_Label_DisplayName {
            get {
                return ResourceManager.GetString("ImageClassificationVissl_Label_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path to the image file..
        /// </summary>
        public static string ImageClassificationVissl_Path_Description {
            get {
                return ResourceManager.GetString("ImageClassificationVissl_Path_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string ImageClassificationVissl_Path_DisplayName {
            get {
                return ResourceManager.GetString("ImageClassificationVissl_Path_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detects objects in images..
        /// </summary>
        public static string ObjectDetectionED_Description {
            get {
                return ResourceManager.GetString("ObjectDetectionED_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D Array containing detection boxes..
        /// </summary>
        public static string ObjectDetectionED_DetectionBoxes_Description {
            get {
                return ResourceManager.GetString("ObjectDetectionED_DetectionBoxes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detection Boxes.
        /// </summary>
        public static string ObjectDetectionED_DetectionBoxes_DisplayName {
            get {
                return ResourceManager.GetString("ObjectDetectionED_DetectionBoxes_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array containing detection classes..
        /// </summary>
        public static string ObjectDetectionED_DetectionClasses_Description {
            get {
                return ResourceManager.GetString("ObjectDetectionED_DetectionClasses_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detection Classes.
        /// </summary>
        public static string ObjectDetectionED_DetectionClasses_DisplayName {
            get {
                return ResourceManager.GetString("ObjectDetectionED_DetectionClasses_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of detections..
        /// </summary>
        public static string ObjectDetectionED_Detections_Description {
            get {
                return ResourceManager.GetString("ObjectDetectionED_Detections_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detections.
        /// </summary>
        public static string ObjectDetectionED_Detections_DisplayName {
            get {
                return ResourceManager.GetString("ObjectDetectionED_Detections_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Detection.
        /// </summary>
        public static string ObjectDetectionED_DisplayName {
            get {
                return ResourceManager.GetString("ObjectDetectionED_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path to the image file..
        /// </summary>
        public static string ObjectDetectionED_Path_Description {
            get {
                return ResourceManager.GetString("ObjectDetectionED_Path_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string ObjectDetectionED_Path_DisplayName {
            get {
                return ResourceManager.GetString("ObjectDetectionED_Path_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Scope for executing 4th-IR Activities..
        /// </summary>
        public static string ProcessScope_Description {
            get {
                return ResourceManager.GetString("ProcessScope_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Scope.
        /// </summary>
        public static string ProcessScope_DisplayName {
            get {
                return ResourceManager.GetString("ProcessScope_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password..
        /// </summary>
        public static string ProcessScope_Password_Description {
            get {
                return ResourceManager.GetString("ProcessScope_Password_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ProcessScope_Password_DisplayName {
            get {
                return ResourceManager.GetString("ProcessScope_Password_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The answer to the question..
        /// </summary>
        public static string QuestionAnsweringRBS2_Answer_Description {
            get {
                return ResourceManager.GetString("QuestionAnsweringRBS2_Answer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string QuestionAnsweringRBS2_Answer_DisplayName {
            get {
                return ResourceManager.GetString("QuestionAnsweringRBS2_Answer_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The context..
        /// </summary>
        public static string QuestionAnsweringRBS2_Context_Description {
            get {
                return ResourceManager.GetString("QuestionAnsweringRBS2_Context_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context.
        /// </summary>
        public static string QuestionAnsweringRBS2_Context_DisplayName {
            get {
                return ResourceManager.GetString("QuestionAnsweringRBS2_Context_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answers questions based on the context provided..
        /// </summary>
        public static string QuestionAnsweringRBS2_Description {
            get {
                return ResourceManager.GetString("QuestionAnsweringRBS2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Answering.
        /// </summary>
        public static string QuestionAnsweringRBS2_DisplayName {
            get {
                return ResourceManager.GetString("QuestionAnsweringRBS2_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question being asked..
        /// </summary>
        public static string QuestionAnsweringRBS2_Question_Description {
            get {
                return ResourceManager.GetString("QuestionAnsweringRBS2_Question_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string QuestionAnsweringRBS2_Question_DisplayName {
            get {
                return ResourceManager.GetString("QuestionAnsweringRBS2_Question_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The accuracy of the answer..
        /// </summary>
        public static string QuestionAnsweringRBS2_Score_Description {
            get {
                return ResourceManager.GetString("QuestionAnsweringRBS2_Score_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string QuestionAnsweringRBS2_Score_DisplayName {
            get {
                return ResourceManager.GetString("QuestionAnsweringRBS2_Score_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target language for translation..
        /// </summary>
        public static string TextTranslationTM_ConversionLanguage_Description {
            get {
                return ResourceManager.GetString("TextTranslationTM_ConversionLanguage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Language.
        /// </summary>
        public static string TextTranslationTM_ConversionLanguage_DisplayName {
            get {
                return ResourceManager.GetString("TextTranslationTM_ConversionLanguage_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performs translation of text..
        /// </summary>
        public static string TextTranslationTM_Description {
            get {
                return ResourceManager.GetString("TextTranslationTM_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Translation.
        /// </summary>
        public static string TextTranslationTM_DisplayName {
            get {
                return ResourceManager.GetString("TextTranslationTM_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source text..
        /// </summary>
        public static string TextTranslationTM_Sentence_Description {
            get {
                return ResourceManager.GetString("TextTranslationTM_Sentence_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentence.
        /// </summary>
        public static string TextTranslationTM_Sentence_DisplayName {
            get {
                return ResourceManager.GetString("TextTranslationTM_Sentence_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language of the source text..
        /// </summary>
        public static string TextTranslationTM_SourceLanguage_Description {
            get {
                return ResourceManager.GetString("TextTranslationTM_SourceLanguage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Language.
        /// </summary>
        public static string TextTranslationTM_SourceLanguage_DisplayName {
            get {
                return ResourceManager.GetString("TextTranslationTM_SourceLanguage_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The translated text..
        /// </summary>
        public static string TextTranslationTM_TranslatedText_Description {
            get {
                return ResourceManager.GetString("TextTranslationTM_TranslatedText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated Text.
        /// </summary>
        public static string TextTranslationTM_TranslatedText_DisplayName {
            get {
                return ResourceManager.GetString("TextTranslationTM_TranslatedText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
