//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4thIR.TextUtility.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_4thIR.TextUtility.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads text in an image..
        /// </summary>
        public static string ImageTextExtraction_Description {
            get {
                return ResourceManager.GetString("ImageTextExtraction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Text Extraction.
        /// </summary>
        public static string ImageTextExtraction_DisplayName {
            get {
                return ResourceManager.GetString("ImageTextExtraction_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path to the image file..
        /// </summary>
        public static string ImageTextExtraction_Path_Description {
            get {
                return ResourceManager.GetString("ImageTextExtraction_Path_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string ImageTextExtraction_Path_DisplayName {
            get {
                return ResourceManager.GetString("ImageTextExtraction_Path_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image text..
        /// </summary>
        public static string ImageTextExtraction_Text_Description {
            get {
                return ResourceManager.GetString("ImageTextExtraction_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string ImageTextExtraction_Text_DisplayName {
            get {
                return ResourceManager.GetString("ImageTextExtraction_Text_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document contents..
        /// </summary>
        public static string PDFParsing_Content_Description {
            get {
                return ResourceManager.GetString("PDFParsing_Content_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string PDFParsing_Content_DisplayName {
            get {
                return ResourceManager.GetString("PDFParsing_Content_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes PDF documents..
        /// </summary>
        public static string PDFParsing_Description {
            get {
                return ResourceManager.GetString("PDFParsing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Parsing.
        /// </summary>
        public static string PDFParsing_DisplayName {
            get {
                return ResourceManager.GetString("PDFParsing_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of pages..
        /// </summary>
        public static string PDFParsing_NumberOfPages_Description {
            get {
                return ResourceManager.GetString("PDFParsing_NumberOfPages_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Pages.
        /// </summary>
        public static string PDFParsing_NumberOfPages_DisplayName {
            get {
                return ResourceManager.GetString("PDFParsing_NumberOfPages_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path to PDF document..
        /// </summary>
        public static string PDFParsing_Path_Description {
            get {
                return ResourceManager.GetString("PDFParsing_Path_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string PDFParsing_Path_DisplayName {
            get {
                return ResourceManager.GetString("PDFParsing_Path_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads text from a PDF document..
        /// </summary>
        public static string PDFTextExtraction_Description {
            get {
                return ResourceManager.GetString("PDFTextExtraction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Text Extraction.
        /// </summary>
        public static string PDFTextExtraction_DisplayName {
            get {
                return ResourceManager.GetString("PDFTextExtraction_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Path to PDF document..
        /// </summary>
        public static string PDFTextExtraction_Path_Description {
            get {
                return ResourceManager.GetString("PDFTextExtraction_Path_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string PDFTextExtraction_Path_DisplayName {
            get {
                return ResourceManager.GetString("PDFTextExtraction_Path_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PDF text..
        /// </summary>
        public static string PDFTextExtraction_Text_Description {
            get {
                return ResourceManager.GetString("PDFTextExtraction_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string PDFTextExtraction_Text_DisplayName {
            get {
                return ResourceManager.GetString("PDFTextExtraction_Text_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performs NLP tokenization of text..
        /// </summary>
        public static string TextTokenizationNLP_Description {
            get {
                return ResourceManager.GetString("TextTokenizationNLP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Tokenization NLP.
        /// </summary>
        public static string TextTokenizationNLP_DisplayName {
            get {
                return ResourceManager.GetString("TextTokenizationNLP_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input format. (Format.format).
        /// </summary>
        public static string TextTokenizationNLP_Format_Description {
            get {
                return ResourceManager.GetString("TextTokenizationNLP_Format_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string TextTokenizationNLP_Format_DisplayName {
            get {
                return ResourceManager.GetString("TextTokenizationNLP_Format_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw text or Full path to txt or pdf file..
        /// </summary>
        public static string TextTokenizationNLP_Text_Description {
            get {
                return ResourceManager.GetString("TextTokenizationNLP_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string TextTokenizationNLP_Text_DisplayName {
            get {
                return ResourceManager.GetString("TextTokenizationNLP_Text_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The processed text..
        /// </summary>
        public static string TextTokenizationNLP_TokenizedText_Description {
            get {
                return ResourceManager.GetString("TextTokenizationNLP_TokenizedText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokenized Text.
        /// </summary>
        public static string TextTokenizationNLP_TokenizedText_DisplayName {
            get {
                return ResourceManager.GetString("TextTokenizationNLP_TokenizedText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performs Spacy tokenization of text..
        /// </summary>
        public static string TextTokenizationSpacy_Description {
            get {
                return ResourceManager.GetString("TextTokenizationSpacy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Tokenization Spacy.
        /// </summary>
        public static string TextTokenizationSpacy_DisplayName {
            get {
                return ResourceManager.GetString("TextTokenizationSpacy_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input format. (Format.format).
        /// </summary>
        public static string TextTokenizationSpacy_Format_Description {
            get {
                return ResourceManager.GetString("TextTokenizationSpacy_Format_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string TextTokenizationSpacy_Format_DisplayName {
            get {
                return ResourceManager.GetString("TextTokenizationSpacy_Format_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw text or Full path to txt or pdf file..
        /// </summary>
        public static string TextTokenizationSpacy_Text_Description {
            get {
                return ResourceManager.GetString("TextTokenizationSpacy_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string TextTokenizationSpacy_Text_DisplayName {
            get {
                return ResourceManager.GetString("TextTokenizationSpacy_Text_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The processed text..
        /// </summary>
        public static string TextTokenizationSpacy_TokenizedText_Description {
            get {
                return ResourceManager.GetString("TextTokenizationSpacy_TokenizedText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokenized Text.
        /// </summary>
        public static string TextTokenizationSpacy_TokenizedText_DisplayName {
            get {
                return ResourceManager.GetString("TextTokenizationSpacy_TokenizedText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
